---
- name: wget python2.7 package
  get_url: url=https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz dest=/tmp/
  register: result

- name: unarchive python package
  unarchive: src=/tmp/Python-2.7.10.tgz dest=/tmp/ remote_src=yes

- name: compile parame
  shell: ./configure --enable-shared --enable-loadable-sqlite-extensions --prefix=/usr/local/python27 --with-zlib --with-ssl
  args:
    chdir: /tmp/Python-2.7.10

- name: make install
  shell: make && make install
  args:
    chdir: /tmp/Python-2.7.10

- name: Add lib libraries
  lineinfile: path=/etc/ld.so.conf line=/usr/local/python27/lib

- name: let the lib libraries task offect
  shell: ldconfig

- name: mv old python to /usr/bin/python2.6.6
  shell: mv /usr/bin/python /usr/bin/python2.6.6 && ln -s /usr/local/python27/bin/python2.7 /usr/bin/python

- include: pip.yml
